spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=universidades;encrypt=false;
    # spring.datasource.url=jdbc:mysql:3314/universidades
    username: SA
    password: Tapiabaeza123#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # spring.datasource.driver.class=com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        # spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
        naming.physical-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl



server:
  port: 8080